# natcap/dam-inference-server-cpu:0.0.1
#FROM tensorflow/tensorflow:1.12.0-py3
FROM tensorflow/tensorflow:2.1.0-py3

SHELL ["/bin/bash", "-c"]

RUN apt-get update -y
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable
RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    libspatialindex-c4v5 \
    libffi-dev \
    emacs \
    python3-opencv \
    python3-dev \
    git

# RUN apt-get install -y \
#     gdal-bin \
#     libgdal-dev \
#     python3-gdal
#
# RUN apt install -y \
#     libffi-dev \
#     python3-setuptools \
#     gcc \
#     python3-dev

COPY requirements.txt /usr/local/workspace/
RUN pip install --upgrade pip
RUN pip install pygeoprocessing==1.9.2
RUN pip install -r /usr/local/workspace/requirements.txt

COPY natgeo_dams_model_resnet50_csv_64.h5 /usr/local/workspace/
COPY tensorflow_inference_server.py /usr/local/workspace/

RUN git clone https://github.com/fizyr/keras-retinanet.git /usr/local/keras-retinanet
WORKDIR /usr/local/keras-retinanet
RUN git checkout 1d5f60bd69b2d79776b849bd0a02249c0d38d4b3
RUN pip install . --user
RUN echo export PATH=\$PATH:/root/.local/bin >> /root/.bashrc

WORKDIR /usr/local/workspace
ENTRYPOINT [ \
    "python", "tensorflow_inference_server.py", \
    "natgeo_dams_model_resnet50_csv_64.h5"]
