# natcap/dam-inference-server-cpu:0.0.1
#FROM tensorflow/tensorflow:1.12.0-py3
FROM tensorflow/tensorflow:2.1.0-py3

RUN apt-get update -qq && \
    apt-get install -y \
    emacs \
    libspatialindex-dev \
    python3-pip \
    python3-gdal \
    python3-opencv \
    postgresql-client \
    openssl \
    curl \
    git \
    && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /usr/local/workspace/
RUN pip3 install --no-cache-dir pygeoprocessing==1.9.2
RUN pip3 install --no-cache-dir -r /usr/local/workspace/requirements.txt

COPY natgeo_dams_model_resnet50_csv_64.h5 /usr/local/workspace/
COPY tensorflow_inference_server.py /usr/local/workspace/

WORKDIR /usr/local/workspace
ENTRYPOINT [ \
    "python3", "tensorflow_inference_server.py", \
    "natgeo_dams_model_resnet50_csv_64.h5"]
