FROM tensorflow/tensorflow:2.1.0-gpu-py3

SHELL ["/bin/bash", "-c"]

RUN apt-get update -y
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable
RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    gdal-bin \
    git \
    libffi-dev \
    libgdal-dev \
    libspatialindex-c4v5 \
    python3-dev \
    python3-gdal \
    python3-opencv \
    python3-setuptools \
    wget

WORKDIR /usr/local/gcloud-sdk
RUN wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-284.0.0-linux-x86_64.tar.gz && tar -xvzf google-cloud-sdk-284.0.0-linux-x86_64.tar.gz
RUN ./google-cloud-sdk/install.sh
RUN source /usr/local/gcloud-sdk/google-cloud-sdk/completion.bash.inc
RUN source /usr/local/gcloud-sdk/google-cloud-sdk/path.bash.inc
RUN echo "export PATH=$PATH:/usr/local/gcloud-sdk/google-cloud-sdk/bin" >> /root/.bashrc

RUN git clone https://github.com/fizyr/keras-retinanet.git /usr/local/keras-retinanet
WORKDIR /usr/local/keras-retinanet
RUN git checkout 1d5f60bd69b2d79776b849bd0a02249c0d38d4b3
RUN pip install keras==2.3.1
RUN pip install . --user
RUN echo export PATH=\$PATH:/root/.local/bin >> /root/.bashrc

COPY requirements.txt /usr/local/workspace/
RUN pip install --upgrade pip
RUN pip install pygeoprocessing==2.0.0 --no-deps
RUN pip install -r /usr/local/workspace/requirements.txt

COPY natgeo-dams-1e56a9f3ab62.json /usr/local/workspace/
COPY natgeo_dams_model_resnet50_csv_64.h5 /usr/local/workspace/
COPY start_inference_server.sh /usr/local/workspace/
COPY tensorflow_inference_server.py /usr/local/workspace/

WORKDIR /usr/local/workspace
ENTRYPOINT [ "bash", "start_inference_server.sh" ]
