# natcap/dam-inference-server-cpu:0.0.1
#FROM tensorflow/tensorflow:1.12.0-py3
FROM tensorflow/tensorflow:2.1.0-py3

RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    emacs \
    libspatialindex-dev \
    python3-pip \
    python3-gdal \
    python3-opencv \
    postgresql-client \
    openssl \
    curl \
    git \
    && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /usr/local/workspace/
RUN pip3 install --no-cache-dir pygeoprocessing==1.9.2
RUN pip3 install --no-cache-dir -r /usr/local/workspace/requirements.txt

COPY natgeo_dams_model_resnet50_csv_64.h5 /usr/local/workspace/
COPY tensorflow_inference_server.py /usr/local/workspace/

RUN git clone https://github.com/fizyr/keras-retinanet.git /usr/local/keras-retinanet
WORKDIR /usr/local/keras-retinanet
RUN git checkout 1d5f60bd69b2d79776b849bd0a02249c0d38d4b3
RUN pip install . --user
RUN echo export PATH=\$PATH:/root/.local/bin >> /root/.bashrc

WORKDIR /usr/local/workspace
ENTRYPOINT [ \
    "python3", "tensorflow_inference_server.py", \
    "natgeo_dams_model_resnet50_csv_64.h5"]
